[package]
name = "grid-aware-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
dotenvy = "0.15.7"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
sqlx =  { version = "0.8.0", features = ["postgres", "runtime-tokio-native-tls"] }
