services:
  server:
    image: tmitchell1234/grid-aware-server
    container_name: server
    environment:
      DATABASE_URL: "postgres://postgres:gridaware@timescaledb-container:5435/gridaware"
      RUST_BACKTRACE: "full"
    networks:
      - shared-server-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

networks:
  shared-server-network:
    driver: bridge
    external: true